services:
  notable-app:
    read_only: false

    volumes:
      - "./storage:/var/www/html/storage:rw"
      - "./app:/var/www/html/app:rw"
      - "./bootstrap:/var/www/html/bootstrap:rw"
      - "./config:/var/www/html/config:rw"
      - "./database:/var/www/html/database:rw"
      - "./resources:/var/www/html/resources:rw"
      - "./routes:/var/www/html/routes:rw"
      - "./public:/var/www/html/public:rw"
      - "./.env:/var/www/html/.env:rw"
